### PR TITLE
Fixed wrong source code formating

### PR DESCRIPTION
**Pull request by hipertracker**
The original source code does not keep any JavaScript convections and it's not readable. I have submitted properly formated source code by Webstorm 9. Why the heck are those huge indentations??

### CODE REVIEW

**Comment by appsforartists** [comment]
I didn't have time to fully write and proofread this before the talk, but [here's our style guide](https://github.com/appsforartists/ambidex/blob/master/STYLE_GUIDE.md).  

Part of being experimental is being experimental with style.  For the last few years, I've been column aligning k/v pairs, and I find it to be much easier to read.  I realize that this is a preference (and that if it isn't something you've seen before, you could very well disagree).

When ES7 classes + mixins land, I may very well reconsider, but for now, I'm closing this.

Thanks for giving Ambidex a look.  Of course, you are welcome to format your own code (that calls Ambidex) however you like.

**Comment by appsforartists** [comment]
(A sidebar on human psychology and tact:  When I see a commit called "Fixed wrong source code formating" and the change is purely implementing someone else's stylistic preference, I'm automatically inclined to decline it.  My monkey-brain thinks "it's not wrong - I wrote it that way on purpose".

If the issue said "hey, people who are new to this project as used to seeing X - maybe we should consider it," I would have had a much different impression.

I'm not closing this out of spite, and I am reconsidering the style as more people see it, but as a git pro-tip, you may be more effective at landing PRs if you're more thoughtful in your commit messages.

Thanks again for looking/suggesting.)

**Comment by hipertracker** [comment]
It was not just huge indentations which does not fit on the screen and inside Github container (you have to scroll the frame to see the source!), but also 
- a [trailing comma](https://github.com/appsforartists/ambidex-example--bike-index/blob/master/application/bike-index/components/BikeDetails.jsx#L11) in the array
- using strings for object keys and not using harmony idiomatic code: ``{"render": function () {...}` instead of just `render() {...}`
- [overcomplex, double parsing construct](https://github.com/appsforartists/ambidex-example--bike-index/blob/master/application/bike-index/components/BikeDetails.jsx#L74) like 

```
{ `${ component.manufacturerName } ${ component.modelName }` }
```

instead of simple

```
${component.manufacturerName} ${component.modelName}
```

**Comment by hipertracker** [comment]
Why not to keep standard JavaScript conventions used everyone? [http://javascript.crockford.com/code.html](http://javascript.crockford.com/code.html)

**Pull request closed without merging**
